### ISSUE TITLE
Persona switch does not honor config values

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#1002]
After upgrading from 1.40 to 1.43.1, the persona config values no longer override the default config.
E.g. with this configuration, my tests do switch between personas, i.e. `currentPersona.id.should == "altTenant"` passes, but the `tenantId` value is still 770.

```/* default persona's tenantId */
tenantId = 111

personas {
    mainTenant {
        /* same as default persona, but an explicit Persona is used for clarity in MT tests */
        tenantId = 111
    }
    altTenant {
        tenantId = 222
    }
}
```

**Comment by MykolaGolubyev** [comment]
Oh no! Sorry about that. 
many chance you can add a e2e feature test to replicate so then I can jump on and add a fix?

**Comment by tsiq-clemens** [comment]
working on it...

**Comment by tsiq-clemens** [comment]
getting stuck compiling webtau for some reason, but this is the test I have in mind:
```
scenario('context example') {
    cfg.email.should == "default@email.send"
    Alice {
       step("do something in context of Alice") {
           customAction()
           cfg.email.should == "alice@email.send"
       }
    }

    Bob {
        step("do same thing in context of Bob") {
            customAction()
            cfg.email.should == "bob@email.send"
        }
    }
}
```

**Comment by MykolaGolubyev** [comment]
did you figure out build issue?

**Comment by MykolaGolubyev** [comment]
added PR #1003, test passes. Feel free to add more logic to the PR

**Comment by tsiq-clemens** [comment]
still sorting it out. webta-cli-testing is unhappy. Might be related to my OS upgrade where openjdk-8 disappeared

**Comment by tsiq-clemens** [comment]
Finally getting there. Had to update Firefox, set some default JDK's, etc.
The test above passes for me as well, which is great, but I'm puzzled now why that is not working in my actual environment.
With v1.40 I have no trouble. Any inspirations?

**Comment by MykolaGolubyev** [comment]
Could you print the values in your setup?
Debugging stand-alone test script from IDE could reveal some cfg internal issue as well

**Comment by tsiq-clemens** [comment]
I'll give it a go when I get a sec, might be tomorrow

**Comment by MykolaGolubyev** [comment]
any luck here?

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens?
