### ISSUE TITLE
How have you responded to the log4j2 vunerability?

### ISSUE THREAD

**Issue by aplatypus** [testingisdocumenting/webtau#1043]
* When using this project/tool we nned to know which build /release is protected against log4j2.

I would recommend a top of page annotation for the readme page...

Thanks for the good work so far.  Merry Christmas

**Comment by MykolaGolubyev** [comment]
Hi, thanks for the issue.
I will need to double check, but I feel like there is no log4j usage (at least not direct) inside Webtau

**Comment by MykolaGolubyev** [comment]
no direct log4j usage
