### ISSUE TITLE
Allow disabling entire scenario file by adding prefix to a name

### ISSUE THREAD

**Issue by Akson** [testingisdocumenting/webtau#1091]
I.e. testFoo.groovy -> DISABLED_testFoo.groovy should disable all scenarios in that file.

**Comment by MykolaGolubyev** [comment]
I like the idea in genera! need to think on naming convention. As there is a chance someone actually has a file name something like `disabled_exchange.groovy`

**Comment by MykolaGolubyev** [comment]
Starting implementation using `<name>.disabled.groovy`
