### ISSUE TITLE
BrowserCookies inaccessible - Java compile error

### ISSUE THREAD

**Issue by aplatypus** [testingisdocumenting/webtau#1116]
**problem**

* I have a REST call set-up  using JUnit5 
* Following the guide here: 
  * https://testingisdocumenting.org/webtau/browser/cookies
  * I set-up a session cookie as shown below.

```
import org.testingisdocumenting.webtau.junit5.WebTau;
import static org.testingisdocumenting.webtau.WebTauDsl.*;

public class MonitorTest{
      :
    public void testListOperation() {
    
        String  name   = "test1";

        browser.cookies.add("session-cookie", "39213277680471245987");
        http.get
        (
            "http://localhost:1234/api/v1/list/"+ name, (header, body) -> 
            {
                :
```
* This code give the compiler error:
   `error: add(String,String) in BrowserCookies is defined in an`  **`inaccessible class or interface`**
 `browser.cookies.add("session-cookie", "39213277680471245987");`
* When I looked, indeed the `BrowserCookies` class is default `package private`.
   * For this to work, `BrowserCookies` needs to be public
   * It may work for Groovy, I think Goovy is more forgiving on this.

**expected**

* Following the guide I expected that the `BrowserCookies`  would have public access
* Alternatively, if you want to keep it private then please add an interface to the `Browser` class to manage cookies.

**system** 

* Target: Java 1.8
* Gradle 
```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          17.0.1 (Azul Systems, Inc. 17.0.1+12-LTS)
OS:           Linux 5.13.0-41-generic amd64
```

**Comment by MykolaGolubyev** [comment]
Oh!
Thanks for reporting and investigation. 
Need to add more Java tests. 
will fix for the upcoming release.

**Comment by aplatypus** [comment]
* That's good thanks. 
* All those interfaces exposed in the `WebTauDsl` need to be public to be used outside the `org.testingisdocumenting.webtau.browser` package.
* It is probably good to check everything declared as: `public final ... ` like `Browser` and `BrowserCookies` exposed in the interface and make sure they are package public access.

* Also I personally prefer this for reasons stated
  *  [Use static imports rarely](http://www.javapractices.com/topic/TopicAction.do?Id=195)
  *  It is perfectly feasinble to for example (when cookies are public) and a lot clearer about what's happening:
```
import org.testingisdocumenting.webtau.WebTauDsl;
    :  
     WebTauDsl.browser.cookies.add("session", "3921327768047958650");
```

**Comment by MykolaGolubyev** [comment]
Good points. 
Regarding static imports I agree in general but in the context of testing I lean towards static to simplify imports, make it easier to discover and a few other things like REPL. Same goes for singletons usage in webtau for config and some other things. I wouldn’t use them in business apps but makes things way easier for user when writing tests and have access to config instance

**Comment by MykolaGolubyev** [comment]
Just realized something. 
In your example, you may need to call cookies set after a page is opened as cookies are for a specific domain.

**Comment by aplatypus** [comment]
* That may be a problem.  This is a REST call to a service that needs the session Id from an authority service.
* No sessionID no response (as a security measure)
* With something like POSTMAN  or in Java I add the session ID to the message (i'd have to go back to see how that's done).

_Thanks for the tip_

**Comment by aplatypus** [comment]
* Some good news:  YES the WebTau `BrowserCookies` worked when I made the test program with Groovy.
  * So that's something for people ... Convert your test to Groovy
* One tip we use Lombok to get a logger: `@Log4j2` -- Groovy didn't work with that
  * Need to use the Apache annotation: `@groovy.util.logging.Log4j2`
    [@groovy.util.logging.Log4j2](http://docs.groovy-lang.org/docs/groovy-2.4.2/html/documentation/#xform-Log4j2)

**Comment by MykolaGolubyev** [comment]
could you please elaborate on your test? 
What I did in a similar situation is pass auth things via HTTP rest calls using `http.header` or implicit header provider for authorization testing. 

Also curios to understand what is the usage of logging inside the test. Webtau tries to capture a lot of data into report and I wonder if more ways to capture that data is required. Will be happy to add them.

Also if you ever want to chat about your use cases (voice or chat messages) - do let me know!

**Comment by MykolaGolubyev** [comment]
I am thinking to put a few more small PRs and cut a release. If you have any inconveniences or suggestions on any webtau topic - do let me know - will bundle them together

**Comment by aplatypus** [comment]
* I mentioned elsewhere that we use JUnit5 which is run by Gradle.
* JUnit seems to capture what we need, otherwise  we use log4j2 in the test class 
* Logging in the test is for diagnostice while we are under development
  * When  test fails -- You need to know what failed and how
  * Most of the time we rely on assert-s
  * We had things fail in library software, and you need to know what settings were used, etc
* I am working on making a test against a REST servlet I'm bound to find fresh speed-humps to navigate.
I've found the discussion page but maybe you should consider a topic area on StackOverflow that Q&A styls suite new comers better I think.
