### ISSUE TITLE
Issues with webtau file upload / download

### ISSUE THREAD

**Issue by t0r0X** [testingisdocumenting/webtau#1419]
I've stumbled across some issues with webtau file upload and download. Following the manual section https://testingisdocumenting.org/webtau/HTTP/body#form-file-data :

### Issue 1
In the examples it isn't clear that `Path` is `java.util.Path`. This question ist acentuated by the mentioned function `testResourcePath()` which is not part of the `webtau` libraries. I've simply replaced that call with `Paths.get(...)`. Maybe adding an import in the examples would defuse the confusion.

### Issue 2
Uploading files with multipart `http.post` sets the `Accept` header to a wrong default value (details below), which leads to obscure 406 HTTP responses ("org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation").
E.g.
```
    http.post(PATH_TO_STUFF + '/' + stuff.getUuid() + SUBPATH_PROFILEIMAGE,
        http.formData(map("file", Paths.get("testfile.png"))));
```
=> bad `Accept` header arriving to backend:
```
POST //localhost:8086/api/doesnotmatter/1a52e17d-f977-460d-95d9-6ab805544a1c/profileimage HTTP/1.1
Content-Type: multipart/form-data; boundary=webtau368621331e2999d96-b50c-4f64-a271-bd6a5b4c6309
Accept: multipart/form-data; boundary=webtau368621331e2999d96-b50c-4f64-a271-bd6a5b4c6309
User-Agent: webtau/1.51
Host: localhost:8086
Connection: keep-alive
Content-Length: 16237
```
=> HTTP 406.

Adding explicit `Accept` header solves this:
```
    http.post(PATH_TO_STUFF + '/' + stuff.getUuid() + SUBPATH_PROFILEIMAGE,
        http.header("Accept", "*/*"),
        http.formData(map("file", Paths.get("testfile.png"))))
```
=> "good" Accept header arrives on backend:
```
POST //localhost:8086/api/doesnotmatter/1a52e17d-f977-460d-95d9-6ab805544a1c/profileimage HTTP/1.1
Content-Type: multipart/form-data; boundary=webtau1305363078b8f0c80e-40e9-4fdd-bebc-fb6bddfb231b
Accept: */*
User-Agent: webtau/1.51
Host: localhost:8086
Connection: keep-alive
Content-Length: 16239
```
=> HTTP 201

### Issue 3
Downloading (`http.get`) a binary file uses `application/json` as default `Accept` header. If this is documented somewhere, I couldn't find it. Maybe it slipped me, then sorry, my issue ;-)
E.g.
```
http.get(PATH_TO_STUFF + '/' + stuff.getUuid() + SUBPATH_PROFILEIMAGE)
```
=> `Accept` header is `application/json`:
```
GET //localhost:8086/api/v1/dateien/21c01d92-899a-40f0-bcd6-d336cf7e8b8c HTTP/1.1
Content-Type: application/json
Accept: application/json
User-Agent: webtau/1.51
Host: localhost:8086
Connection: keep-alive
```

The solution is again to set the `Accept` header explicitly:
```
http.get(PATH_TO_STUFF + '/' + stuff.getUuid() + SUBPATH_PROFILEIMAGE, http.header("Accept", "*/*"))
```

I guess the main confusion source is in fact Spring Boot, which is terribly bad a telling what is wrong: the sent `Content-Type`  or the `Accept`.

### Issue 4
Does webtau have a option to enable logging/tracing of sent/received HTTP headers, which could be activated only for some requests? I had to trace instead on the Spring Boot side, which is tedious.

### ~~Issue 5~~
~~Headers: can't iterate with `headers.foreach(it -> ...)`~~
Solved: my mistake/confusion: ìteration through headers has to be done with `headers.getResponseHeader().forEachProperty((key, value) -> ...)`.

**Comment by MykolaGolubyev** [comment]
Hi Victor,
thank you for the very detailed issue

First of all, are you blocked at the moment? Trying to interpret `BLOCKING: ` parts of the issue.

Appreciate the successful investigation and sorry you had to go through it.
BTW,  header values are present in generated HTML report. Need to think how to include it to console (maybe a config value to toggle).

Looking at the data you provided, it could be that `boundary=` somehow interfere with the SpringBoot.
Do you by any chance have a sample app/controller to reproduce?

You are right that `http.get` defaults to application/json. It was done as majority of responses we encounter is json. I wonder if it should be */* now. Need to think on consequences. E.g. what if an end point starts to return XML :) What do you think?

**Comment by t0r0X** [comment]
Hello Mykola,

no, I'm not blocked anymore, since I found out the `Accept`-Header workaround. I composed the text a while, and forgot to remove the BLOCKING marker. If it's ok with you I'll redact it.

I see also that I forgot to write about the most "blocking" issue, where I don't have a workaround, I'll add it too.

**Comment by t0r0X** [comment]
Hello Mykola,
I've rephrased/reformatted the issue text, and in the meanwhile I understood my mistake with "Issue 5", so that's one is not an issue anymore.

**Comment by t0r0X** [comment]
> Looking at the data you provided, it could be that boundary= somehow interfere with the SpringBoot.
Do you by any chance have a sample app/controller to reproduce?

Sure, I will try to setup a small stand-alone example, but it may take until next week.

**Comment by MykolaGolubyev** [comment]
Do you have any immediate suggestions to add to webtau to the upcoming release?

**Comment by MykolaGolubyev** [comment]
Also wanted to confirm if you were able to generate/look at the generated report

**Comment by t0r0X** [comment]
> Do you have any immediate suggestions to add to webtau to the upcoming release?

Nothing small enough to be implemented in few hours/days ;-).

**Comment by t0r0X** [comment]
> Also wanted to confirm if you were able to generate/look at the generated report

Yes, thanks for pointing that out! I helped me few minutes ago to diagnose a test error, where I was using the wrong uuid:
![image](https://user-images.githubusercontent.com/9170345/231615503-1fca3bd4-e1b2-4b86-a027-f03c75e38dcc.png)

I now wonder if I should store the test report HTML in the artifacts stored with the Jenkins builds... I suppose I should and will.

**Comment by MykolaGolubyev** [comment]
> > Do you have any immediate suggestions to add to webtau to the upcoming release?
> 
> Nothing small enough to be implemented in few hours/days ;-).

Now you made me curios. What do you have in mind?

**Comment by MykolaGolubyev** [comment]
@t0r0X?
