### ISSUE TITLE
Set properties cannot be compared with TableData

### ISSUE THREAD

**Issue by clemensbertram** [testingisdocumenting/webtau#156]
Example:
Set aSet = myBean.getChildrenSet()
aSet.should == [ ... table data ...] // throws exception that Set cannot be converted to a List.
aSet.toList().should == [ ... table data ...] // works fine

This prevents sub collection matching if I want to verify properties of myBean, e.g.
myBean.should == [ propA: 'expectedA', childrenSet: expectedChildrenTableData ]

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens do you want to take a stub at this?

**Comment by tsiq-karold** [comment]
What are the proposed semantics of this comparison?  A set is often unordered whereas a table feels like it would generally be ordered.

**Comment by MykolaGolubyev** [comment]
I think a default set order of iteration should suffice. Especially for cases with LinkedHashSet. Or TreeSet. 
TableData has a notion of key columns, but it is not being used for comparisons yet. When matching by key is implemented, then underlying collection wouldn’t matter.

**Comment by MykolaGolubyev** [comment]
@clemensbertram do you still want to implement this?

**Comment by tsiq-clemens** [comment]
this hasn't come up as a priority again, happy to close the book on this for now

**Comment by MykolaGolubyev** [comment]
I was hoping you could PR :)
I think it is a reasonable request
