### ISSUE TITLE
Implement a caching auth provider

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#162]
We have a couple of auth provider implementations now which basically do the same thing when asked for a token:

- check local cache file and its validity (in terms of time expiry)
- if valid, great
- if not valid, fetch new token and cache it

Would be nice for webtau to have some sort of helper class/utils to make this easier and reduce the duplication.

**Comment by tsiq-nick** [comment]
Sounds like a good idea. On the other hand webtau doesn't know anything about auth at the moment. It has header provider and navigation page open handlers.
