### ISSUE TITLE
anyOf syntax

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#208]
Right now there is no nice way to express `fieldFoo.should == 1 or 2` (simplest case, there are more complex cases).  Would be nice to have syntax such as `fieldFoo.shouldBe anyOf(1, 2)` which will lend itself naturally to other extensions such as `fieldFoo.shouldBe anyOf(greaterThan(3), lessThan(-5), 100)`.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold peer pressuring you here :)

**Comment by tsiq-karold** [comment]
Did we ever agree what the syntax should look like? I thought we had discussed it but I don't see the discussion on the issue :(

**Comment by MykolaGolubyev** [comment]
True. I do recall talking about it. 
how about a.should == anyOf(value, orMatcher, orAnythingReallyThatCanBePartOfConpareToHandlers)

**Comment by tsiq-karold** [comment]
That was my favourite though I thought we'd come up with some objections. I might be mixing it up with something else though.  I'm still happy to implement this, I just can't commit to when.
