### ISSUE TITLE
Support iterating over values of response object

### ISSUE THREAD

**Issue by tsiq-rob** [testingisdocumenting/webtau#214]
Sometimes a JSON object in a response is encoding a String->Object map, and it's useful to be able to iterate over the values of that object.

At the moment, one has to do

```
body.asMap().values().each { ... }
```
There is already a function `keySet()` for getting the set of keys of an object so perhaps a similar function could be added for getting the collection of values.

**Comment by MykolaGolubyev** [comment]
how about adding `children().each {}`? 
Or would you prefer `.eachChildren()` ?

**Comment by MykolaGolubyev** [comment]
Closing as there are alternatives
