### ISSUE TITLE
Expose performance data to custom report generators

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#219]

**Comment by MykolaGolubyev** [comment]
@tsiq-karold remind me, were you going to tackle this one?

**Comment by tsiq-karold** [comment]
I was but I won't get to it for a while so if you have time and a need for it then go ahead.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold Is it still needed?

**Comment by tsiq-karold** [comment]
I can't remember the context of why I wanted this :)

In general I do think that custom reports should have access to the same data as the http report but I don't know if that is the case. Either way, I would suggest we close this issue and reopen if we do find something missing.
