### ISSUE TITLE
Support for warnings and general reporting for Swagger validation

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#22]
The primary usecase is to warn about URLs which were invoked but not part of the spec.  Some other things we could include would be to add the model in either another tab in the report or inline in steps for example.

**Comment by MykolaGolubyev** [comment]
Will swagger tab contain description and path params as well?
What is the primary use case?

**Comment by MykolaGolubyev** [comment]
@tsiq-karold any ideas on this one?

**Comment by tsiq-karold** [comment]
I think the use case I had in mind was for reporting when a particular <method, path> is not found in the spec.  We don't fail on that, just spit out a warning to the console but it would be nice to have it included in the report also.
