### ISSUE TITLE
Transformations for doc capture

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#221]
This should be used sparingly but for list responses for example, it's likely that in docs you'll only want one or two items.  Supporting transformations at capture time will allow one to use somewhat sophisticated logic for selecting what to show in docs.

**Comment by tsiq-karold** [comment]
Discussed this with @MykolaGolubyev, we propose the syntax listed below.  This is based on an example response:
```json
{
   "ints": [1,2,3,4,5],
    "strings": ["a", "b", "ab", "abc", "ba"]
}
```

Simple response filter:
```groovy
http.doc.filterResponse('ints', anInt -> anInt > 3)
```
Would generate:
```json
{
   "ints": [4,5],
    "strings": ["a", "b", "ab", "abc", "ba"]
}
```

Multiple filters:
```groovy
http.doc
    .filterResponse('ints', anInt -> anInt > 3)
    .filterResponse('strings', str -> str.startsWith('a')
    .capture()
```
Would generate:
```json
{
    "ints": [4,5],
    "strings": ["a", "ab", "abc"]
}
```

The reason for the fluid API with `filterResponse` methods is to allow us to later add filtration of requests, headers, etc.

Such capture calls should capture the unfiltered body in the existing path/filename and the filtered body in a file with a `filtered` infix (i.e. `response.filtered.json`).

**Comment by MykolaGolubyev** [comment]
Is this still relevant?

**Comment by MykolaGolubyev** [comment]
@tsiq-karold ^

**Comment by tsiq-karold** [comment]
It's relevant in that we still don't have support for it but I don't have a need for it any more.
