### ISSUE TITLE
Refactor compare to handler tests

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#281]
Particularly the messages test which seems to touch most, if not all, handlers.

**Comment by tsiq-karold** [comment]
This issue is the result of this discussion: https://github.com/twosigma/webtau/pull/279#pullrequestreview-207127593

**Comment by MykolaGolubyev** [comment]
Looks like we are not doing it yet, closing to reduce the issues noise ratio.
