### ISSUE TITLE
timeout cli testing after a time of inactivity

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/webtau#339]
we need to have a way out if if CLI process that was ran as part of webtau test runs for too long

**Comment by MykolaGolubyev** [comment]
@tsiq-karold should we have a fixed timeout or more like inactivity timeout (i.e. if for 10 seconds there is no output, but if there is - reset timer)?

**Comment by tsiq-karold** [comment]
Definitely at least a fixed timeout but it would be nice to have an inactivity timeout also.  Travis for example has both.
