### ISSUE TITLE
Make http, ui and cli doc capture to be a TestStep

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/webtau#358]
Lets wrap doc capture to be its own TestStep. I.e. we need to wrap the actual logic inside `doc.capture` with `TestStep.createAndExecuteStep` (similarly how we made OpenAPI validation to be its own step).

**Comment by tsiq-karold** [comment]
Out of interest, why?

**Comment by MykolaGolubyev** [comment]
Make sure action is part of report logs. 
Have a way to check if the test took time due to docs logic vs other logic. E.g. screenshot annotation process.

**Comment by tsiq-clemens** [comment]
would Webtau users be interested in seeing those as separate steps, though?

**Comment by MykolaGolubyev** [comment]
What is the alternative?

**Comment by tsiq-clemens** [comment]
as a user, I might be interested in seeing those additional timing details in the summary where you already have start time, execution time, etc. rather than in a test step. 
They feel more like attributes of the whole execution (ReportTestEntry) rather than at the TestStep level.

**Comment by MykolaGolubyev** [comment]
Coming back to this - doc capture is not a report specific activity. You also may have 5 different doc captures sprinkled across a test. 
Additionally in case if browser testing it is also an additional validation that element is present. 
I think ideally everything should be a test step. Main benefit is discovering what happened in a test when it is broken.
