### ISSUE TITLE
Remove jitpack dependency

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#376]
Would be nice to remove the dependency on jitpack because webtau users need it too.  I can't remember right now what comes from it.

**Comment by MykolaGolubyev** [comment]
I am confused to what is using jitpack as well. I noticed you added
```
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```
do you remember what issue it was solving?

**Comment by MykolaGolubyev** [comment]
I figured it is required for `com.github.everit-org.json-schema`

**Comment by tsiq-karold** [comment]
This also has some licensing issues as mentioned in #438.  We probably don't need both issues?
