### ISSUE TITLE
Allow programmatically setting configuration options

### ISSUE THREAD

**Issue by mattmetlis** [testingisdocumenting/webtau#420]
I'd like to enable programmatic access to setting the configuration options. This will make it easier and cleaner to set the config options with internal TS tooling, where env files are not always supported and to allow us to specify these options the way configuration is commonly specified in Java codebases, e.g. through non-env property files.

**Comment by MykolaGolubyev** [comment]
@mattmetlis not sure if it is documented yet, but there is `webtau.properties` way to specify a config for java based tests. 
Also there is `WebTauConfigHandler` that you can implement and provide your own config values injections. 

We should improve Java specific docs for sure. Do you want to help with that?

**Comment by mattmetlis** [comment]
I'm happy to improve the docs. I might want to go through and create Java examples for a lot of the Groovy examples that currently exist. We're going to explore writing tests using Groovy also.

For WebTauConfigHandler, it looks like I would implement that, and pass an instance to WebTauConfig.registerConfigHandlerAsFirstHandler before making any calls to the test functions like http?

**Comment by MykolaGolubyev** [comment]
`WebTauConfigHandler` is usually registered using `META-INF/services`. You can take a look at the existing implementations of the interface.

**Comment by mattmetlis** [comment]
Awesome, I can accomplish what I need with a custom implementation of WebTauConfigHandler. I'll create a separate ticket for documenting that and I'll close this one.

**Comment by tsiq-karold** [comment]
I thought the handlers were largely for internal webtau usage.  Is there a reason using a `WebTauConfigHandler` is preferable over doing `getCfg().acceptConfigValues()` from a `BeforeAll`?  Or using `setBaseUrl` (which I use successfully) or one of the `get*ConfigValue().set()` options?  The latter two don't have full coverage of cfg options though.

**Comment by MykolaGolubyev** [comment]
My understanding that it was to provide a sensible default for tests across different codebases. More like a thin wrapper of webtau for internal usage.

**Comment by MykolaGolubyev** [comment]
I am curious about the use case even more now. Could you please elaborate on it?

**Comment by MykolaGolubyev** [comment]
@mattmetlis after I read the usecase I still think that you could create a `WebTauConfigHandler` that would use TS internal magic to figure out the path and inject the calculated path into the config.

**Comment by mattmetlis** [comment]
It certainly would work, but this is functionality we want developers to be able to see and modify. Since there are already ways to set the other config values currently, I think it makes sense to add the same option for the spec URL.

**Comment by MykolaGolubyev** [comment]
Does it mean you will have to do it in `@BeforeAll` in each test? I also don't envision people setting `baseUrl` this way in each test. It sort of breaks the whole environments concept. In best case scenario people should be able to run the subset of tests in different envs without fiddling with the code.

There could be a hybrid approach of auto setup using `WebTauConfigHandler` and `webtau.properties`. So if someone sets api path value using `webtau.properties` file then `WebTauConfigHandler` does nothing, otherwise it uses default logic to set the api spec path.

**Comment by MykolaGolubyev** [comment]
Not an issue at the moment
