### ISSUE TITLE
Add Javadocs to hosted GitHub docs

### ISSUE THREAD

**Issue by mattmetlis** [testingisdocumenting/webtau#421]
Hosting the Javadocs on GitHub (in addition to the guide which is already hosted) would be helpful for understanding how to use WebTau.

**Comment by MykolaGolubyev** [comment]
I wonder if we should add reference section to the docs themselves. 
I am not a big user of javadocs, so curios what kind of information you are looking for mostly.

**Comment by mattmetlis** [comment]
The primary thing that led me to this request is that I find myself frequently using IntelliJ to click through to the methods I'm calling in my tests to see what different combinations of arguments I can pass. Primarily the post, put, get, etc., but also the assertion methods and methods on the data nodes.

The advantages of javadocs are that they can be generated directly from the source code so they stay in sync, and they're self linked so fairly easy to navigate. The downside is it will show classes that you might not want users using directly, though if there's a good reason for them not to then they probably should be protected in some other way. My concern with a reference section in the existing guide is I think it would have to be manually kept in sync.

**Comment by MykolaGolubyev** [comment]
We use `Znai` for docs and it is using references to the code and real examples with the purpose of it not to become stale.
 
I am for JavaDocs to be up-to-date as well.  In fact `Znai` can reference text of java docs and embed it inside the user guide. 

I think we should have both, with the focus on making official user guide to be easier to follow.

**Comment by mattmetlis** [comment]
That's good to know, I had missed that feature of Znai. It looks like you can reference specific methods or specific docs, but (unless I missed something) answering for the user 'what are all the different overloaded versions of this method' or 'what are all the methods I can call on this class' might be best answered with Javadoc. The Znai inclusion would be useful for providing examples in the guide.

**Comment by mattmetlis** [comment]
By the way, would it make sense to define the various config keys as a list of constants in one place?

**Comment by mattmetlis** [comment]
I created a pull request for generating the javadocs. @tsiq-karold is there any automation right now around the user guide or other docs that I should integrate this with, or is it all manual right now?

**Comment by tsiq-karold** [comment]
There is some.  https://github.com/twosigma/webtau/blob/master/update-gh-pages.sh will update the gh-pages branch with znai generated docs and the znai export.  Modifying it to also add javadocs should hopefully be fairly easy.

The intention was to run that from a release build hence the deploy part in the Travis file: https://github.com/twosigma/webtau/blob/master/.travis.yml#L25

However, getting the permissions to work correctly is likely to be more pain than it's worth so I'm going to remove that from Travis and update https://github.com/twosigma/webtau/blob/master/release.md to say run that script.

**Comment by mattmetlis** [comment]
I've merged the change to be able to generate the javadocs. Will keep this open until I can add them to the update-gh-pages script.

**Comment by MykolaGolubyev** [comment]
Java docs within IDE should be available from maven central.
More reference docs are being added to the znai documentation.
