### ISSUE TITLE
openApiSpecUrl does not work for HTTP URL

### ISSUE THREAD

**Issue by mattmetlis** [testingisdocumenting/webtau#423]
When specifying an HTTP URL (e.g. 'http://localhost:8080/v2/api-docs', which is the URL for the API docs in the demo app in webtau-testapp) for the openApiSpecUrl parameter in a webtau.properties or webtau.cfg file, the test fails because it cannot find the spec:
```
Caused by: java.lang.IllegalArgumentException: Unable to load API descriptor from provided "http:/localhost:8080/v2/api-docs":
	[unable to read location `"http:/localhost:8080/v2/api-docs"`]
	at com.twosigma.webtau.openapi.OpenApiSpec.<init>(OpenApiSpec.java:56)
	at com.twosigma.webtau.openapi.OpenApi.reset(OpenApi.java:49)
	at com.twosigma.webtau.openapi.OpenApiSpecConfig.onAfterCreate(OpenApiSpecConfig.java:45)
	at com.twosigma.webtau.cfg.WebTauConfig.lambda$triggerConfigHandlers$16(WebTauConfig.java:116)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.twosigma.webtau.cfg.WebTauConfig.triggerConfigHandlers(WebTauConfig.java:116)
	at com.twosigma.webtau.cfg.WebTauConfig.<init>(WebTauConfig.java:104)
	at com.twosigma.webtau.cfg.WebTauConfig$CfgInstanceHolder.<clinit>(WebTauConfig.java:376)
	... 31 more
```
You can see in the error message that the double slash in the URL is being converted to a single slash. It looks like this is caused by the OpenApiSpecConfig.java's onAfterCreate method.

**Comment by MykolaGolubyev** [comment]
Revisiting this. Not a big fan of hardcoding base url in the path since we already have a notion of `baseUrl`.
@tsiq-karold I wonder if we should try to resolve the given path using multiple attempts:
1. file based.
2. base url + specified relative path
3. full url in case it starts from http[s]

**Comment by mattmetlis** [comment]
Having "URL" in the name of the variable makes people think that an HTTP URL will work. If you want to keep it only to mean a file path then I suggest renaming it something like "openApiSpecPath".

**Comment by MykolaGolubyev** [comment]
I think URL support makes sense. I was more against specifying full url, as it will be less convenient to deal with multiple environments.

**Comment by tsiq-karold** [comment]
We definitely should support non-file based specs.  I think the naming of that config param was inherited from the library we use for open api validation but clearly we didn't test that when it says URL it actually means that!  Anyway, I think we should try and replace that library, it has many issues, the one in #438 being a particularly bad one.

In terms of resolution, wouldn't it make more sense to check for http/https start first then either get it from the specified URL or attempt 1 and 2 as you defined them?

**Comment by MykolaGolubyev** [comment]
Right, if it looks like full url, we should check it first, then file based, then base url + relative path.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold is this something that you think would be tackled as you look for the alternative libs for schema validation?

**Comment by tsiq-karold** [comment]
Yes, I think so.

**Comment by tsiq-karold** [comment]
I think I got two things confused actually.  #438 is related to the library we use for JSONSchema validation, not OpenAPI.  I have a PR out for #438, will tackle this one next.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold Merry Christmas!!! do you still want to take on this one?
