### ISSUE TITLE
Add more Java examples to REST test docs

### ISSUE THREAD

**Issue by mattmetlis** [testingisdocumenting/webtau#425]
Several of the pages in the REST testing section contain Groovy examples. For example, https://twosigma.github.io/webtau/guide/REST/getting-started#bare-minimum. It would be nice if those sections also had Java examples. The examples could have tabs with one tab for Groovy and another for Java.

**Comment by MykolaGolubyev** [comment]
May help to have a better way to document across languages and runners. We have JUnit4, JUnit5, TestNG, Groovy custom runner and we have Java and Groovy. 
Created Znai ticket: https://github.com/twosigma/znai/issues/288

**Comment by MykolaGolubyev** [comment]
#1153
