### ISSUE TITLE
Support relaxed certificate validation for non-production environments

### ISSUE THREAD

**Issue by tsiq-anindya** [testingisdocumenting/webtau#455]
Tests are often run against sites with self-signed certs and adding a cert to the Java trust store within an AWS lambda (for example) is not possible without overriding the trust store and supplying a custom one.
In webtau-http
`HttpURLConnection connection = (HttpURLConnection) new URL(fullUrl).openConnection();`
Can webtau be modified to return either HttpsURLConnection or HttpURLConnection depending on what new URL returned, so that we can override the SSL context within the groovy test script.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold, is this by any chance something you need as well ;) ?

**Comment by MykolaGolubyev** [comment]
@tsiq-anindya I am not very well versed in SSL specifics, could you please elaborate more on the approach you are going to take?

**Comment by tsiq-anindya** [comment]
I suggest having a function within webtau-http that allows for the SSL context to be changed. The first step would be to return the appropriate type as I mentioned in the question, followed by a public function `allowInsecureRequests()` perhaps, with a custom trust store within:
```
TrustManager[] trustAllCerts = new TrustManager[] {new X509TrustManager() {
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return null;
                }
                public void checkClientTrusted(X509Certificate[] certs, String authType) {
                }
                public void checkServerTrusted(X509Certificate[] certs, String authType) {
                }
            }
        };
```
This custom truststore is then installed with the following code:
```
SSLContext sslContext = SSLContext.getInstance("SSL");
sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
http.setDefaultSSLSocketFactory(sc.getSocketFactory());
```
http must be of type HttpsURLConnection for this to work, I suppose you could assert for that.

It might also be helpful for some integration testing schemes to disable hostname validation. This can be done with `setDefaultHostnameVerifier` in the `HttpsURLConnection` class.

**Comment by tsiq-karold** [comment]
I chatted with @tsiq-anindya  on Friday and I think I understand what he’s requesting, I’m happy to take this issue.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold great, thank you!
For my benefit, what would the test code look like? I am a bit confused with "step would be to return the appropriate type". Return from where and to who?

**Comment by tsiq-karold** [comment]
There’s a few ways to test this, I’ll need to do a bit of research to work out which will be easiest/simplest.

**Comment by MykolaGolubyev** [comment]
Do we still need this?

**Comment by tsiq-anindya** [comment]
I'd already figured a work-around back then by loading certs onto a custom certstore, but I'm sure people would find this feature useful regardless.

**Comment by MykolaGolubyev** [comment]
what was the workaround?
@tsiq-karold do you see anything that can be added to webtau?

**Comment by tsiq-karold** [comment]
I honestly can't remember the details of this but I don't think it's terribly pressing, I'd suggest closing.
