### ISSUE TITLE
expose report path through maven plugin

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/webtau#459]
Config values are defined in: `com.twosigma.webtau.cfg.WebTauConfig`
Maven plugin entry point: `com.twosigma.webtau.maven.WebTauMavenRun`
Config key to expose: `reportPath`

**Comment by tsiq-karold** [comment]
Might be a good idea to find a way to convert any plugin config into webtau cfg so we don't have to keep adding fields to `WebTauMavenRun` (or the other one whose name escapes me).

**Comment by MykolaGolubyev** [comment]
Would be nice for sure. From what I know about maven plugins is that you need to declare each field so xml validation take place. Or do you suggest to pass like a blob or something?

**Comment by tsiq-karold** [comment]
Not an expert on Maven plugins by any means but I think there is a way to just have a configuration node and get a hold of all child nodes.  I don't know what it is though.

**Comment by oneemo95** [comment]
Duplicate of #174 
Duplicate of #125 
Duplicate of #135 
Duplicate of #945 
Duplicate of #777

**Comment by MykolaGolubyev** [comment]
@oneemo95 what is going on?
