### ISSUE TITLE
No put override without a validator

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#499]
One can do `http.post(url, body)` without a `{}` but one cannot do that for `http.put(url, body)`.

**Comment by MykolaGolubyev** [comment]
Is this something you will PR for?

**Comment by tsiq-karold** [comment]
Yes.

**Comment by MykolaGolubyev** [comment]
@tsiq-karold will you have time, or do you want me to do it?

**Comment by tsiq-karold** [comment]
I've been struggling to find time to do any webtau work so go ahead.
