### ISSUE TITLE
Update user docs for GraphQL

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#584]

**Comment by MykolaGolubyev** [comment]
wonder if `prism.js` already has `GraphQL` syntax highlight. 
Would be nice to add native `GraphQL` support to `znai` and be able to highlight certain parts of it. I will take a look at znai side.

**Comment by tsiq-karold** [comment]
It would be nice indeed.  The markdown parser/renderer that GitHub uses supports it but I don't know about prism.

e.g.
```graphql
query foo {
  id 
  description
  count
}
```

**Comment by tsiq-karold** [comment]
Looks like it does: https://prismjs.com/#supported-languages

**Comment by MykolaGolubyev** [comment]
Good. Will enable it. 
When I was talking about highlight I mean more like json specific value highlight. But maybe a single line highlight is enough.

**Comment by tsiq-karold** [comment]
I see. The response is pure json so nothing to add.

For the request query I think line highlighting should be sufficient because if you pretty print it there will mostly be a single name per line anyway. Only exception is the first line which typically will have type (query, mutation, etc), name and args.

**Comment by tsiq-karold** [comment]
Addressed via https://github.com/testingisdocumenting/webtau/pull/635.
