### ISSUE TITLE
GraphQL DSL - initial support

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#585]
* check for 200 instead of 201 as implied by requests being POSTs
* better response data access
* no need to always specify url
* 1st class knowledge of query, variables, etc.

**Comment by MykolaGolubyev** [comment]
Is the plan to add a new 
```
http.graphql(url, ....)
```
?

**Comment by tsiq-karold** [comment]
There isn't a concrete plan yet, @tsiq-clemens and I need to discuss a bit more what we really need.  In all likelihood it would be either `http.graphql(...)` or `graphql.execute(...)` like cli and db depending on exactly what we need.

**Comment by MykolaGolubyev** [comment]
As a user I would like to use a separate graphql namespace. We may need to figure out how to expose some of the implementation details of http to be reused. Things like printing, auto validation, capturing etc

**Comment by tsiq-karold** [comment]
By separate namepsace, you mean `graphql.execute()` (we can argue about the function name later 😁 )? Or something else.

That's my preference currently also btw.

**Comment by MykolaGolubyev** [comment]
Yes

**Comment by MykolaGolubyev** [comment]
As for function names I would map them to whatever most common client libraries use
