### ISSUE TITLE
GraphQL DSL - configurability

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#604]
1. url - in theory it's possible someone may serve at root for example, rather than graphql. It's debatable whether we should do this at all or just force users to stick the graphql path in the base url config.
1. success status code - in case people deviate from best practices
1. invocation method - there are many ways to invoke a graphql service according to best practices: POST bodies like I've used, GET and query params and POST with application/graphql content type. We probably should allow any of these.

**Comment by tsiq-clemens** [comment]
on (1), sticking with the standard `/graphql` path is at the very least a sensible default. Should be easy to make configurable if we hear that it's a limiting factor for a potential webtau user.  Compared to (2) and (3), this seems like a very low priority.

**Comment by tsiq-karold** [comment]
I think in general this whole issue is low priority compared to some of the other issues in https://github.com/testingisdocumenting/webtau/projects/4.

**Comment by MykolaGolubyev** [comment]
closing as no active
