### ISSUE TITLE
GraphQL DSL - wrap execution in a step

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#605]
Similar to how http execution is wrapped in a step.

**Comment by MykolaGolubyev** [comment]
If you delegate to `http.post` then it is going to be double wrapped?

**Comment by tsiq-karold** [comment]
Yes but I thought we supported something along the lines of sub-step?

**Comment by MykolaGolubyev** [comment]
We do. Was asking if we need double step at all. What extra info will you add in the parent step? And how much of it will be repeated in the inner step?

**Comment by tsiq-karold** [comment]
I don't know.  I haven't fully thought through all the issues I raised but I didn't want to forget about them either :)

If we do a bit more processing of the request and response (eg parsing or constructing) then at least the timing element may be useful.

This is relatively low priority though.

**Comment by MykolaGolubyev** [comment]
closing as not active
