### ISSUE TITLE
GraphQL DSL - consider dropping query name from body assertions

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#606]
For example, if one executes this query:
```GraphQL
query {
    allTasks(uncompletedOnly: false) {
        id
        description
    }
}
```
And wishes to assert on the `id` in the response, one has to do:
```groovy
allTasks.id.should == ["a", "b", "c"]
```
We should give the option to omit the `allTasks` part.

**Comment by MykolaGolubyev** [comment]
could you elaborate what prompts this? Does GraphQL always return a root level node?

**Comment by tsiq-karold** [comment]
I'd have to check the spec to know if it does always.  However, in the typical simple examples you'd send something like:
```graphql
query foo {
  id
}
```

The response would then be:
```json
{
  "data": {
    "foo": {
      "id": "abc"
    }
  }
}
```

Webtau can work out that if I do `id.should == "abc"` I really mean `body.data.foo.id` though it'll have to parse the request to do so.
