### ISSUE TITLE
Swagger - error when asserting on fields not in schema

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#638]
If one is asserting that a field is null and makes a typo in the field name then the test will always pass even if the field comes back non-null.

We should validate that the assertion is being made against a field which is actually part of the schema. We will also need to provide a way to turn off this behaviour should someone really want to assert something that does not exist in the schema. e.g.
```groovy
http.get('/foo') {
  suppressUnknownFieldErrors {
    somethingNotInSchema.should == 'foo'
  }
}
```

Related to #637 but we probably cannot handle this generically in HTTP because there may not be a schema.

**Comment by MykolaGolubyev** [comment]
do you still need this one?

**Comment by tsiq-karold** [comment]
I don't need it as such but I do think it would be a useful addition to webtau.

**Comment by MykolaGolubyev** [comment]
I recall you had some implementation around it, is it still somewhere there?

**Comment by tsiq-karold** [comment]
I do not recall that :)

**Comment by MykolaGolubyev** [comment]
closing as not active
