### ISSUE TITLE
Disambiguate identical file names at different points in hierarchy

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#687]
As an example, let's take this directory hierarchy:
```
scenarios
  foo.grooy
  stuff
    foo.groovy
```

If I run webtau with `scenarios/foo.groovy scenarios/stuff/foo.groovy` then in the html report, I just get two sections with a `foo.groovy` file name which is confusing.  We should include the full name, perhaps relative to something though I'm not sure what the something ought to be :)

**Comment by MykolaGolubyev** [comment]
hmm, not sure if someone fixed it in the other PRs, but I can't reproduce it now with 1.41. 
Could you please give it a go again?
