### ISSUE TITLE
GraphQL queries/mutation docs clarification

### ISSUE THREAD

**Issue by MykolaGolubyev** [testingisdocumenting/webtau#697]
We have page called `Queries` but covers queries and mutations. We either rename it to to avoid accidental skipping through it. Or have a separate pages to cover mutations

**Comment by tsiq-karold** [comment]
I think the only sensible thing would be to rename the page to `Queries and Mutations` in line with GraphQL's own docs: https://graphql.org/learn/queries/ though interestingly the link just says `queries` 😁
