### ISSUE TITLE
GraphQL - remove the enabled config flag

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#702]
We should be able to detect by trying an introspection call and then set it enabled or disabled accordingly.

**Comment by MykolaGolubyev** [comment]
Can you remind me why do we even need this flag? We now have graphql.execute.

**Comment by tsiq-karold** [comment]
No because I cannot remember

**Comment by tsiq-karold** [comment]
I suspect just didn't clean it up after adding the graphql dsl
