### ISSUE TITLE
Report file execution time

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#738]
It would be useful to report how long each scenario file took to execute.  When running in parallel mode it's better to have more or less evenly sized scenario files but right now it's hard to evaluate whether that is indeed the case.

**Comment by MykolaGolubyev** [comment]
We already display file execution time on summary page. Do you mean to have a page with all files and their time? Or include that info in navigation panel?

**Comment by tsiq-karold** [comment]
Yes, I meant broken down by file. It's useful for detecting if you have very unbalanced files (in terms of execution time) in a parallel context where that diminishes the benefit of parallel exec.
