### ISSUE TITLE
propagate reporting errors

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#745]
Exceptions handled during report generation are currently just printed to stdout/err and easily missed.
A better way is to collect problems in a List of errors that an HTML/JSON report can display.

**Comment by MykolaGolubyev** [comment]
Are you talking about generic errors or coverage specific errors? Could you please remind me with a few examples?

**Comment by tsiq-clemens** [comment]
In this case we're talking about exceptions encountered during report generation, so after all testing is over. There's currently just 1 spot that could possibly hit such a problem in `GraphQLCoverage::isErrorResult`: 
`JsonUtils.convertToTree(JsonUtils.deserialize(validationResult.getResponse().getTextContent())).has("errors");`
