### ISSUE TITLE
auto-generated scenarios do not work well with metadata

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#765]
Using a metadata enforcer like in the example below leads to failures because auto-generated scenarios are not annotated:
```
class OwnerEnforcer implements TestListener {
    @Override
    void afterLastTestStatement(WebTauTest test) {
        if (!test.metadata.has("owner")) {
            throw new OwnerMissingException(
                "Scenario '${test.scenario}' in '${test.filePath}' is missing an owner, " +
                "please specify one from ${OwnerMetadata.class.getName()}")
        }
    }
}
```

results in errors:
```
  "erroredDetails" : [ {
    "scenario" : "before first test",
    "filePath" : "setup-listeners",
    "exception" : "Scenario 'before first test' in 'setup-listeners' is missing an owner, please specify one from reporting.OwnerMetadata",
    "owner" : null
  }, {
    "scenario" : "after all tests",
    "filePath" : "teardown-listeners",
    "exception" : "Scenario 'after all tests' in 'teardown-listeners' is missing an owner, please specify one from reporting.OwnerMetadata",
    "owner" : null
  } ],
  "erroredScenarios" : [ "before first test", "after all tests" ],
```

**Comment by tsiq-clemens** [comment]
a working workaround checks whether the `test.scenario` is not one of those 2 scenarios, but that's rather hacky

**Comment by MykolaGolubyev** [comment]
Should we add a flag saying it is webtau generated scenario?

**Comment by tsiq-clemens** [comment]
would `synthetic` be metadata itself? I can see that work

**Comment by MykolaGolubyev** [comment]
I was thinking top level test field to denote that test is auto generated. 
Can be both.

**Comment by tsiq-clemens** [comment]
if it's metadata then there's a chance/danger that an unsuspecting metadata user overwrites/reuses it; top-level might be safer in that respect

**Comment by MykolaGolubyev** [comment]
Want to take a stab at it? It has been awhile ;)

**Comment by tsiq-clemens** [comment]
yeah, why not. I'm getting rusty

**Comment by tsiq-clemens** [comment]
As I'm looking at this, I wondered why there's no failing webtau test for the owner enforcement and I found that webtau's `MetadataValidationTestListener` avoids the problem by adding a check `test.hasSteps()`. If that is a valid solution, meaning `hasSteps() == isSynthetic()`, then we can close this issue.

**Comment by MykolaGolubyev** [comment]
I wouldn't really on `hasSteps` meaning it is synthetic. One reason is certain things that are not wrapped into a step may be in future. And certain things like `cli.backgroundRun` are being shutdown at the very end if they were not explicitly shutdown and that will add steps to the `clean up` synthetic test.
