### ISSUE TITLE
Default values for HttpResponseValidatorWithReturn

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#836]
I think it would be nice if `HttpResponseValidatorWithReturn` had the ability to return "default" values other than `null`.  This is probably better illustrated with an example:
```groovy
scenario("test") {
  List list = http.get() {
    return listItemInResponse
  }
}
```

Right now, regardless of whether `listItemInResponse` is null or `[]`, `list` is null.

I think we should consider two changes:
1. if `listItemInResponse` is `[]` then `list` should be `[]`.  This in fact seems like a bug.
2. if `listItemInResponse` is null, we should offer the option of returning an empty list, perhaps controlled via a param or cfg setting.

I'm personally not 100% convinced about item 2 but item 1 I think we definitely should fix.

**Comment by tsiq-karold** [comment]
Hmmm, I tried to create a test to reproduce this in webtau and couldn't :(

This is the contents of `emptyNestedListResponse.json`:
```json
{
  "things": []
}
```
I then register it:
```java
handler.registerGet("/empty-list", jsonResponse("emptyNestedListResponse.json"));
```
And the actual test:
```groovy
    @Test
    void "empty list"() {
        List things = http.get("/empty-list") {
            return things
        }

        things.shouldNot == null
        things.should == []
    }
```

So I think this might be something on our end or it may need to be more complex than this.  I'll do some more debugging.

**Comment by MykolaGolubyev** [comment]
should I close this one?

**Comment by tsiq-karold** [comment]
Yes, I'll have to dig into our code a bit more if this resurfaces and I'll re-open if it is indeed something in webtau.
