### ISSUE TITLE
Configurable redaction

### ISSUE THREAD

**Issue by tsiq-karold** [testingisdocumenting/webtau#837]
Right now we redact some well known headers such as `Authorization`.  It would be great to provide configuration to redact:
1. other headers
2. paths within a body as some auth systems seem to return tokens in the response body

**Comment by MykolaGolubyev** [comment]
I like it. Let's make the default ones also to go away? 
I.e. for testing local servers and systems sometimes it is annoying to see the absence of header values. 
And then for env like `uat`, `staging`, etc set the value to `true` and specify additional paths?

**Comment by tsiq-karold** [comment]
The flag makes sense but I'm wondering if we should default to redaction on.  It'll be on in more envs than off and it won't be a breaking change.

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens is this something you can tackle?

**Comment by tsiq-clemens** [comment]
I'll try to make time when I'm back from spring break

**Comment by MykolaGolubyev** [comment]
@tsiq-clemens do you guys still need it?

**Comment by tsiq-clemens** [comment]
Sorry, been heads down in other endeavors. It's a nice-to-have, possibly needs a bit more thought, but I do not see myself finding the time to look at this in the immediate future.
