### ISSUE TITLE
requests that time out report incorrect start time

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#844]
![webtau-timeout](https://user-images.githubusercontent.com/43554128/109990502-72287900-7cd7-11eb-9f8a-741a6be21a34.png)

* one problem is that after upgrading to webtau-1.38 (defaulting the http connection's `connectTimeout` and `readTimeout` to 30s), we see SocketTimeout exceptions that we did not get before. The corresponding requests on the backend appear to have finished in milliseconds to a few seconds, whereas webtau reports the scenario as >30s
* steps that show a timeout are reported with a `19:00:00.000` start time, which probably means that its `startTime` was never set to the current time, meaning `startClock()` never happened.

`Http`'s `executeAndValidateHttpCall` has a try-finally clause, but no catch, is that part of the problem?

```
        try {
            return step.execute(StepReportOptions.REPORT_ALL);
        } finally {
            lastValidationResult.set(validationResult);
            step.addPayload(validationResult);
        }
```

**Comment by MykolaGolubyev** [comment]
One issue regarding missing start time I understand.  Looks like a bug.
Could you please elaborate on what do you mean by 
> The corresponding requests on the backend appear to have finished in milliseconds to a few seconds
I wonder if the actual data transfer and other layers or AWS add time that it timeouts. We use default Java HTTP timeout, not a 3rd party library, so I would assume it works as expected.
Can you find your previous successful reports and check if there were any calls in that slow response percentile? 

I am actually looking at the issue unrelated to http step but more like any `WebTauStep` potentially not capturing data on errors, but not sure yet. 
It maybe just http related. Will dig in

**Comment by tsiq-clemens** [comment]
what I meant is that although >30s were reported, the underlying service only took <1s, so it's a mystery what added 29 seconds to the roundtrip.
