### ISSUE TITLE
capture arbitrary artifacts

### ISSUE THREAD

**Issue by tsiq-clemens** [testingisdocumenting/webtau#872]
Today http.doc.capture can grab artifacts for inclusion in docs.
Sometimes it's useful to capture arbitrary objects (e.g. JSON) that are derived from query results, example:
1. I'm accumulating responses from a succession of calls (e.g. long-polling notification events)
2. I want to include one (or all) of those accumulated responses in my doc
3. I want to show off how to follow up with a different http call that uses data (some ID) from the accumulated response

If I use a hardcoded example in (2) but a doc capture for (3), the ID's never match up and confuse the reader.

Proposal:
* Make `Capture` first-class
* allow capture of arbitrary content, passing in
  * name
  * file type (some enum of options, e.g. json, txt, ...) 
  * contents
* store contents in "data.<fileType>"

**Comment by tsiq-clemens** [comment]
Thinking a bit more about it, we could take it a step further and allow for multiple files to be stored with custom file names, so http capture naturally becomes an extension of this, capturing various request and response files.

**Comment by MykolaGolubyev** [comment]
Take a look at `doc.capture` available in webtau core. It already handles some data types. 
We may need to do some `inversion of control` to avoid exposing `DataNode` class to `core` module. We can discuss implementation details. Or you can call `toMap` or something on data node and pass it to `doc.capture`

**Comment by MykolaGolubyev** [comment]
Regarding you comment on multiple files. I may need to think more about it.`http.doc.capture` doesn't use `doc.capture`. But it does share the location and utilities used. Maybe that is enough.

**Comment by MykolaGolubyev** [comment]
Did you have a chance to read my reply?

**Comment by tsiq-clemens** [comment]
just got back from vacation and found what you're talking about in webtau-core. I'll give it a go, thanks.

**Comment by tsiq-clemens** [comment]
`doc.captureJson` works for me, I'll close this for now.
